FROM ubuntu:latest
RUN apt-get -y update && apt-get -y install mariadb

# Set up mariadb database
COPY sql-config.sql /tmp/sql-config.sql
CMD [ "/usr/bin/mariadb", "-u root -proot < /tmp/sql-config.sql;"]
